### ISSUE TITLE
Use on `cpu` ?

### ISSUE THREAD

**Issue by tim-habitat** [StatMixedML/Py-BoostLSS#3]
Is there anyway we can use the package on a `cpu` ? 
If so, anything would need to be adjusted ?

**Comment by StatMixedML** [comment]
@tim-habitat Thanks for your interest in the project.

> Is there anyway we can use the package on a cpu ?

I am afraid no. Since the models are developed for runtime efficiency, both the base Py-Boost and Py-BoostLSS models work only on GPU.
