### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'concatenate'

### ISSUE THREAD

**Issue by waminos** [StatMixedML/Py-BoostLSS#4]
**I just tried to implement the example, it trains successfully but then when predict i have this error.
Can you help solve this error pls ?**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_24/401963851.py in <module>
      1 # Predicts transformed parameters of the specified distribution. Py-BoostLSS returns the elements of the covariance matrix, instead of the Cholesky factors.
----> 2 predt_params = distribution.predict(model=pyboostlss_model,X_test=x_test,pred_type="parameters")
      3 predt_params

/kaggle/working/Py-BoostLSS/pyboostlss/distributions/MVN.py in predict(self, model, X_test, pred_type, n_samples)
    239 
--> 240         params_predt = [response_fun(params_predt[:, i]).reshape(-1,1) for i, (dist_param, response_fun) in enumerate(param_dict.items())]
    241 
    242         # Location

AttributeError: module 'torch' has no attribute 'concatenate'

**Comment by StatMixedML** [comment]
@waminos Thanks for your interest in the project.

I cannot replicate the error (pytorch 1.13.0+cu117). 

Can you please check what pytorch version you are using.

**Comment by waminos** [comment]
> @waminos Thanks for your interest in the project.
> 
> I cannot replicate the error (pytorch 1.13.0+cu117).
> 
> Can you please check what pytorch version you are using.

![image](https://user-images.githubusercontent.com/18538948/207280681-81e9ca6d-233d-4031-b07e-53e20e72b25e.png)

**Comment by StatMixedML** [comment]
Can you please update to the latest torch version pytorch 1.13.0+cu110 and re-try.

**Comment by waminos** [comment]
Thanks ! Upgrading my version solved it
